"""Creating influencer_post

Revision ID: 02265e07be14
Revises: 
Create Date: 2019-11-13 00:28:02.448417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02265e07be14'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('influencer_post',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('influencer', sa.String(), nullable=True),
    sa.Column('instagram_url', sa.String(), nullable=True),
    sa.Column('caption', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('influencer_post')
    # ### end Alembic commands ###
