"""Post

Revision ID: 0d7089551eec
Revises: 
Create Date: 2019-12-21 18:11:08.371356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d7089551eec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('influencer', sa.String(), nullable=True),
    sa.Column('img_file', sa.String(), nullable=True),
    sa.Column('influencer_caption', sa.String(), nullable=True),
    sa.Column('alt_text', sa.String(), nullable=True),
    sa.Column('instagram_post_hash', sa.String(), nullable=True),
    sa.Column('caption', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    # ### end Alembic commands ###
