"""Base64 image

Revision ID: 6ddc43f74fef
Revises: 6f82bd4d3fa8
Create Date: 2019-12-15 13:59:22.086242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ddc43f74fef'
down_revision = '6f82bd4d3fa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('img_base64', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'img_base64')
    # ### end Alembic commands ###
