"""Renaming to Post


Revision ID: 6f82bd4d3fa8
Revises: b5a2c527199c
Create Date: 2019-12-15 13:57:30.641848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f82bd4d3fa8'
down_revision = 'b5a2c527199c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('influencer', sa.String(), nullable=True),
    sa.Column('img_insta_url', sa.String(), nullable=True),
    sa.Column('influencer_caption', sa.String(), nullable=True),
    sa.Column('caption', sa.String(), nullable=True),
    sa.Column('alt_text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('influencer_post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('influencer_post',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('influencer', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('caption', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('alt_text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('img_insta_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='influencer_post_pkey')
    )
    op.drop_table('post')
    # ### end Alembic commands ###
