"""Adding alt text

Revision ID: b5a2c527199c
Revises: 02265e07be14
Create Date: 2019-11-16 20:16:03.439950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5a2c527199c'
down_revision = '02265e07be14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('influencer_post', sa.Column('alt_text', sa.String(), nullable=True))
    op.add_column('influencer_post', sa.Column('img_insta_url', sa.String(), nullable=True))
    op.drop_column('influencer_post', 'instagram_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('influencer_post', sa.Column('instagram_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('influencer_post', 'img_insta_url')
    op.drop_column('influencer_post', 'alt_text')
    # ### end Alembic commands ###
