"""Post created_at updated_at

Revision ID: ce312177546d
Revises: 0d7089551eec
Create Date: 2019-12-22 10:12:50.229449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce312177546d'
down_revision = '0d7089551eec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('post', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'updated_at')
    op.drop_column('post', 'created_at')
    # ### end Alembic commands ###
