"""Adding img_file

Revision ID: e85106e1ec60
Revises: 2a1be877e107
Create Date: 2019-12-15 14:33:49.580459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e85106e1ec60'
down_revision = '2a1be877e107'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('img_file', sa.String(), nullable=True))
    op.drop_column('post', 'img_base64')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('img_base64', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('post', 'img_file')
    # ### end Alembic commands ###
